name: Forest Bathing
favicon: null
layout_spectrum: 0.16788442712277174
typography_spectrum: 0.891403857152909
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6574505071621388
  lightness: 0.6530492824967951
  saturation: 0.2865567891858518
  rhythmicContrast: 0.21521013509482145
purpose: []
